name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.6.4
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  cloud_firestore: ^5.4.0
  connectivity_plus: ^2.3.7
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  dart_code_metrics: ^4.21.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_chat_types:
    # path: ./flutter_chat_types
    git:
      url: https://github.com/marctan/flutter_chat_types.git